# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Chris <goabonga@pm.me>

blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/goabonga/cloud/tree/rebuild/cloud/docs
    about: Read the documentation available in the reconstruction branch
