# Micro-VM demo: a 3-node kubeadm cluster. A real VM per node under
# infra-hypervisor (infra_microvm), not a namespaced container like
# ../compute's infra_compute: one control plane and two workers, seeded
# entirely by cloud-init - no image baked for either role. Stock kubeadm, not
# a lighter distribution: each micro-VM gets enough CPU/RAM to clear
# kubeadm's own preflight checks (2 vCPUs, 2048MiB - the minimum is 1700MiB).
# See ../vm for a single VM without kubeadm's extra weight.
#
# Bootstrap order matters once, at creation: the workers' user-data embeds
# the control plane's address, which the agent only assigns once it
# reconciles the resource - asynchronously, not within this apply. Create the
# control plane on its own first:
#   terraform apply -target=infra_microvm.k8s_control_plane
# wait for it to reach Ready and for kubeadm to come up (dashboard, or poll
# `terraform show`), then apply the rest:
#   terraform apply
# A single `terraform apply` from scratch also works for everything *except*
# the workers, whose join command would otherwise embed an empty address.

# A key pair for this demo alone, generated by Terraform rather than supplied
# from the operator's own ~/.ssh - the private half only ever surfaces
# through `terraform output`, never written to disk by this config.
resource "tls_private_key" "k8s" {
  algorithm = "ED25519"
}

resource "infra_vpc" "demo" {
  cidr = "10.20.0.0/16"
}

locals {
  # Not a secret: the k8s subnet is private to this VPC, reachable only from
  # inside it or through infra's own firewalling. Fixed rather than
  # kubeadm-generated so the control plane and a worker agree on it without a
  # second apply; must match kubeadm's token format (6 lowercase
  # alphanumerics, a dot, 16 more).
  k8s_join_token = "lab0k8.demojointoken001"
  k8s_vmlinuz    = "/var/lib/infra-microvm-images/vmlinuz"
  k8s_initrd     = "/var/lib/infra-microvm-images/initrd.img"
  k8s_image      = "/var/lib/infra-microvm-images/noble-base.raw"
  # No bootloader under direct kernel boot, so the root partition has to be
  # named explicitly; vda1 matches the base image's layout (see
  # ansible/roles/microvm).
  k8s_cmdline = "console=ttyS0 root=/dev/vda1 rw"

  # Shared by both roles: the SSH key, swap off, the kernel modules and
  # sysctls kubeadm's preflight checks require, and containerd plus the
  # kubeadm/kubelet/kubectl packages from the upstream apt repository. A "#!"
  # user-data script, not "#cloud-config" - see domain/resource/microvm.go -
  # so there is nowhere a YAML block's indentation could get in the way.
  k8s_common = join("\n", [
    "#!/bin/bash",
    "set -euo pipefail",
    "",
    "mkdir -p /home/ubuntu/.ssh",
    "echo '${trimspace(tls_private_key.k8s.public_key_openssh)}' >> /home/ubuntu/.ssh/authorized_keys",
    "chown -R ubuntu:ubuntu /home/ubuntu/.ssh",
    "chmod 700 /home/ubuntu/.ssh",
    "chmod 600 /home/ubuntu/.ssh/authorized_keys",
    "",
    "swapoff -a",
    "",
    "cat >/etc/modules-load.d/k8s.conf <<'EOF'",
    "overlay",
    "br_netfilter",
    "EOF",
    "modprobe overlay",
    "modprobe br_netfilter",
    "",
    "cat >/etc/sysctl.d/k8s.conf <<'EOF'",
    "net.bridge.bridge-nf-call-iptables  = 1",
    "net.bridge.bridge-nf-call-ip6tables = 1",
    "net.ipv4.ip_forward                 = 1",
    "EOF",
    "sysctl --system",
    "",
    "export DEBIAN_FRONTEND=noninteractive",
    "apt-get update",
    "apt-get install -y apt-transport-https ca-certificates curl gnupg containerd",
    "",
    "mkdir -p /etc/containerd",
    "containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' >/etc/containerd/config.toml",
    "systemctl restart containerd",
    "",
    "mkdir -p /etc/apt/keyrings",
    "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg",
    "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' >/etc/apt/sources.list.d/kubernetes.list",
    "apt-get update",
    "apt-get install -y kubelet kubeadm kubectl",
    "apt-mark hold kubelet kubeadm kubectl",
  ])
}

resource "infra_subnet" "k8s" {
  vpc_id = infra_vpc.demo.id
  cidr   = "10.20.2.0/24"
  type   = "private"
}

resource "infra_security_group" "k8s" {
  vpc_id = infra_vpc.demo.id
  name   = "k8s"
}

# Lab simplification: one rule opens the whole k8s subnet to itself rather
# than enumerating kubeadm's exact ports (6443, 10250, etcd's 2379/2380,
# flannel's VXLAN 8472/udp, ...), plus SSH for debugging.
resource "infra_security_group_rule" "k8s_internal" {
  security_group_id = infra_security_group.k8s.id
  direction         = "ingress"
  protocol          = "all"
  cidr              = infra_subnet.k8s.cidr
}

resource "infra_security_group_rule" "k8s_ssh" {
  security_group_id = infra_security_group.k8s.id
  direction         = "ingress"
  protocol          = "tcp"
  port              = 22
  cidr              = "0.0.0.0/0"
}

resource "infra_microvm" "k8s_control_plane" {
  name              = "k8s-cp"
  hostname          = "k8s-cp"
  subnet_id         = infra_subnet.k8s.id
  security_group_id = infra_security_group.k8s.id
  vcpus             = 2
  memory_mb         = 2048
  kernel_path       = local.k8s_vmlinuz
  initrd_path       = local.k8s_initrd
  cmd_line          = local.k8s_cmdline
  image             = local.k8s_image

  user_data = join("\n", [
    local.k8s_common,
    "kubeadm init --pod-network-cidr=10.244.0.0/16 --token=${local.k8s_join_token} --token-ttl=0",
    "mkdir -p /home/ubuntu/.kube",
    "cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config",
    "chown -R ubuntu:ubuntu /home/ubuntu/.kube",
    "KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml",
  ])
}

resource "infra_microvm" "k8s_worker" {
  for_each = toset(["node-1", "node-2"])

  name              = "k8s-${each.key}"
  hostname          = "k8s-${each.key}"
  subnet_id         = infra_subnet.k8s.id
  security_group_id = infra_security_group.k8s.id
  vcpus             = 2
  memory_mb         = 2048
  kernel_path       = local.k8s_vmlinuz
  initrd_path       = local.k8s_initrd
  cmd_line          = local.k8s_cmdline
  image             = local.k8s_image

  # Ordering only: the control plane must be created (and reconciled by the
  # agent, which assigns its address) before a worker's user-data can embed
  # the join address. See the bootstrap note above - this does not by itself
  # make a single `terraform apply` safe for the workers.
  depends_on = [infra_microvm.k8s_control_plane]

  user_data = join("\n", [
    local.k8s_common,
    # The join token is fixed (see k8s_join_token) rather than the one
    # `kubeadm init` would otherwise print, and discovery skips verifying the
    # control plane's CA hash - neither is known before the control plane has
    # actually booted and run it, which a single apply cannot wait for.
    # Acceptable inside this lab's own private subnet; not a pattern for a
    # real cluster.
    "kubeadm join ${infra_microvm.k8s_control_plane.ip}:6443 --token=${local.k8s_join_token} --discovery-token-unsafe-skip-ca-verification",
  ])
}

output "k8s_control_plane_ip" {
  description = "Address of the k8s control-plane micro-VM."
  value       = infra_microvm.k8s_control_plane.ip
}

output "k8s_worker_ips" {
  description = "Addresses of the k8s worker micro-VMs."
  value       = { for k, v in infra_microvm.k8s_worker : k => v.ip }
}

output "k8s_phases" {
  description = "Lifecycle phase of every k8s micro-VM: Ready once infra-hypervisor has booted it."
  value = merge(
    { "k8s-cp" = infra_microvm.k8s_control_plane.phase },
    { for k, v in infra_microvm.k8s_worker : "k8s-${k}" => v.phase }
  )
}

output "k8s_ssh_private_key" {
  description = "Private half of the key pair generated for this demo (terraform output -raw k8s_ssh_private_key, then ssh -i <(that) ubuntu@<ip>)."
  value       = tls_private_key.k8s.private_key_openssh
  sensitive   = true
}
