# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Chris <goabonga@pm.me>
---
- name: Restart systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted

- name: Reload systemd-networkd
  ansible.builtin.command: networkctl reload
  changed_when: true
