// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Chris <goabonga@pm.me>

import {
  AlertTriangle,
  Boxes,
  Cpu,
  DoorOpen,
  FileText,
  Globe,
  HardDrive,
  Key,
  KeyRound,
  Link2,
  Network,
  Route as RouteIcon,
  Scale,
  Server,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  Tag,
  Target,
  Waypoints,
} from "lucide-react";

import type { ResourceDef } from "./types";

// RESOURCES is keyed by kind and mirrors KINDS in api/generic.ts one-to-one
// (enforced by registry.test.ts). listColumns/searchableFields are dot-paths
// drawn from each kind's Go spec/status struct in
// internal/domain/resource/*.go.
export const RESOURCES: Record<string, ResourceDef> = {
  vpc: {
    kind: "vpc",
    label: "VPC",
    pluralLabel: "VPCs",
    category: "networking",
    icon: Network,
    listColumns: [
      { key: "spec.cidr", label: "CIDR" },
      { key: "status.bridgeName", label: "Bridge" },
    ],
    searchableFields: ["spec.cidr"],
  },
  subnet: {
    kind: "subnet",
    label: "Subnet",
    pluralLabel: "Subnets",
    category: "networking",
    icon: Waypoints,
    listColumns: [
      { key: "spec.vpcId", label: "VPC" },
      { key: "spec.cidr", label: "CIDR" },
      { key: "spec.type", label: "Type" },
      { key: "status.gateway", label: "Gateway" },
    ],
    searchableFields: ["spec.vpcId", "spec.cidr"],
  },
  security_group: {
    kind: "security_group",
    label: "Security group",
    pluralLabel: "Security groups",
    category: "security",
    icon: ShieldCheck,
    listColumns: [
      { key: "spec.vpcId", label: "VPC" },
      { key: "spec.name", label: "Name" },
      { key: "status.chain", label: "Chain" },
    ],
    searchableFields: ["spec.vpcId", "spec.name"],
  },
  security_group_rule: {
    kind: "security_group_rule",
    label: "Firewall rule",
    pluralLabel: "Firewall rules",
    category: "security",
    icon: ShieldAlert,
    listColumns: [
      { key: "spec.securityGroupId", label: "Security group" },
      { key: "spec.direction", label: "Direction" },
      { key: "spec.protocol", label: "Protocol" },
      { key: "spec.port", label: "Port" },
      { key: "spec.cidr", label: "CIDR" },
    ],
    searchableFields: ["spec.securityGroupId", "spec.cidr"],
  },
  ip_address: {
    kind: "ip_address",
    label: "IP address",
    pluralLabel: "IP addresses",
    category: "networking",
    icon: Globe,
    listColumns: [
      { key: "spec.type", label: "Type" },
      { key: "status.address", label: "Address" },
      { key: "spec.subnetId", label: "Subnet" },
      { key: "spec.computeId", label: "Compute" },
    ],
    searchableFields: ["status.address", "spec.address"],
  },
  igw: {
    kind: "igw",
    label: "Internet gateway",
    pluralLabel: "Internet gateways",
    category: "networking",
    icon: DoorOpen,
    listColumns: [
      { key: "spec.vpcId", label: "VPC" },
      { key: "status.hostIface", label: "Host interface" },
    ],
    searchableFields: ["spec.vpcId"],
  },
  route: {
    kind: "route",
    label: "Route",
    pluralLabel: "Routes",
    category: "networking",
    icon: RouteIcon,
    listColumns: [
      { key: "spec.vpcId", label: "VPC" },
      { key: "spec.destination", label: "Destination" },
      { key: "spec.gateway", label: "Gateway" },
    ],
    searchableFields: ["spec.vpcId", "spec.destination"],
  },
  kms_keyring: {
    kind: "kms_keyring",
    label: "KMS keyring",
    pluralLabel: "KMS keyrings",
    category: "security",
    icon: KeyRound,
    listColumns: [{ key: "spec.name", label: "Name" }],
    searchableFields: ["spec.name"],
  },
  kms_key: {
    kind: "kms_key",
    label: "KMS key",
    pluralLabel: "KMS keys",
    category: "security",
    icon: Key,
    listColumns: [
      { key: "spec.keyringId", label: "Keyring" },
      { key: "spec.name", label: "Name" },
      { key: "spec.purpose", label: "Purpose" },
      { key: "spec.algorithm", label: "Algorithm" },
    ],
    searchableFields: ["spec.keyringId", "spec.name"],
  },
  disk: {
    kind: "disk",
    label: "Disk",
    pluralLabel: "Disks",
    category: "storage",
    icon: HardDrive,
    listColumns: [
      { key: "spec.name", label: "Name" },
      { key: "spec.sizeMb", label: "Size (MB)" },
      { key: "status.encrypted", label: "Encrypted" },
    ],
    searchableFields: ["spec.name"],
  },
  disk_file: {
    kind: "disk_file",
    label: "Disk file",
    pluralLabel: "Disk files",
    category: "storage",
    icon: FileText,
    listColumns: [
      { key: "spec.diskId", label: "Disk" },
      { key: "spec.path", label: "Path" },
      { key: "spec.mode", label: "Mode" },
    ],
    searchableFields: ["spec.diskId", "spec.path"],
  },
  compute: {
    kind: "compute",
    label: "Compute instance",
    pluralLabel: "Compute instances",
    category: "compute",
    icon: Cpu,
    listColumns: [
      { key: "spec.name", label: "Name" },
      { key: "spec.subnetId", label: "Subnet" },
      { key: "spec.image", label: "Image" },
      { key: "status.ip", label: "IP" },
    ],
    searchableFields: ["spec.name", "spec.image", "status.ip"],
  },
  acl_policy: {
    kind: "acl_policy",
    label: "ACL policy",
    pluralLabel: "ACL policies",
    category: "security",
    icon: ShieldX,
    listColumns: [
      { key: "spec.rules.length", label: "Rules" },
      { key: "status.appliedRules", label: "Applied" },
    ],
    searchableFields: [],
  },
  dns_zone: {
    kind: "dns_zone",
    label: "DNS zone",
    pluralLabel: "DNS zones",
    category: "dns",
    icon: Globe,
    listColumns: [
      { key: "spec.domain", label: "Domain" },
      { key: "spec.visibility", label: "Visibility" },
      { key: "spec.vpcIds.length", label: "VPCs" },
    ],
    searchableFields: ["spec.domain"],
  },
  dns_record: {
    kind: "dns_record",
    label: "DNS record",
    pluralLabel: "DNS records",
    category: "dns",
    icon: Tag,
    listColumns: [
      { key: "spec.zoneId", label: "Zone" },
      { key: "spec.name", label: "Name" },
      { key: "spec.type", label: "Type" },
      { key: "spec.records.length", label: "Values" },
    ],
    searchableFields: ["spec.zoneId", "spec.name"],
  },
  peering: {
    kind: "peering",
    label: "VPC peering",
    pluralLabel: "VPC peerings",
    category: "networking",
    icon: Link2,
    listColumns: [
      { key: "spec.vpc1Id", label: "VPC 1" },
      { key: "spec.vpc2Id", label: "VPC 2" },
    ],
    searchableFields: ["spec.vpc1Id", "spec.vpc2Id"],
  },
  load_balancer: {
    kind: "load_balancer",
    label: "Load balancer",
    pluralLabel: "Load balancers",
    category: "loadbalancing",
    icon: Scale,
    listColumns: [
      { key: "spec.vpcId", label: "VPC" },
      { key: "spec.port", label: "Port" },
      { key: "spec.protocol", label: "Protocol" },
      { key: "status.address", label: "Address" },
    ],
    searchableFields: ["spec.name", "status.address"],
  },
  lb_backend: {
    kind: "lb_backend",
    label: "LB backend",
    pluralLabel: "LB backends",
    category: "loadbalancing",
    icon: Target,
    listColumns: [
      { key: "spec.lbId", label: "Load balancer" },
      { key: "spec.computeId", label: "Compute" },
      { key: "spec.port", label: "Port" },
      { key: "spec.weight", label: "Weight" },
    ],
    searchableFields: ["spec.lbId", "spec.computeId"],
  },
  waf_policy: {
    kind: "waf_policy",
    label: "WAF policy",
    pluralLabel: "WAF policies",
    category: "security",
    icon: AlertTriangle,
    listColumns: [
      { key: "spec.targetType", label: "Target type" },
      { key: "spec.targetId", label: "Target" },
      { key: "status.chain", label: "Chain" },
    ],
    searchableFields: ["spec.targetId"],
  },
  waf_rule: {
    kind: "waf_rule",
    label: "WAF rule",
    pluralLabel: "WAF rules",
    category: "security",
    icon: AlertTriangle,
    listColumns: [
      { key: "spec.policyId", label: "Policy" },
      { key: "spec.matchType", label: "Match type" },
      { key: "spec.action", label: "Action" },
    ],
    searchableFields: ["spec.policyId"],
  },
  node: {
    kind: "node",
    label: "Node",
    pluralLabel: "Nodes",
    category: "compute",
    icon: Server,
    listColumns: [
      { key: "spec.hostname", label: "Hostname" },
      { key: "spec.address", label: "Address" },
      { key: "spec.capacity.cpus", label: "CPUs" },
      { key: "spec.capacity.memoryMb", label: "Memory (MB)" },
    ],
    searchableFields: ["spec.hostname", "spec.address"],
  },
  node_pool: {
    kind: "node_pool",
    label: "Node pool",
    pluralLabel: "Node pools",
    category: "compute",
    icon: Boxes,
    listColumns: [
      { key: "spec.name", label: "Name" },
      { key: "status.readyNodes", label: "Ready" },
      { key: "status.totalNodes", label: "Total" },
    ],
    searchableFields: ["spec.name"],
  },
};
