// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Chris <goabonga@pm.me>

import {
  AlertTriangle,
  Box,
  Boxes,
  Building2,
  Cpu,
  Crosshair,
  DoorOpen,
  FileText,
  Folder,
  FolderKanban,
  Globe,
  HardDrive,
  Key,
  KeyRound,
  Layers,
  Link2,
  Network,
  Radio,
  Route as RouteIcon,
  Scale,
  Server,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  Tag,
  Target,
  UserCog,
  Waypoints,
} from "lucide-react";

import type { ResourceDef } from "./types";

// RESOURCES is keyed by kind and mirrors KINDS in api/generic.ts one-to-one
// (enforced by registry.test.ts). listColumns/searchableFields/fields are
// drawn from each kind's Go spec/status struct and its Validate() method in
// internal/domain/resource/*.go.
export const RESOURCES: Record<string, ResourceDef> = {
  vpc: {
    kind: "vpc",
    label: "VPC",
    pluralLabel: "VPCs",
    category: "networking",
    icon: Network,
    listColumns: [
      { key: "spec.cidr", label: "CIDR" },
      { key: "status.bridgeName", label: "Bridge" },
    ],
    searchableFields: ["spec.cidr"],
    fields: [{ key: "cidr", label: "CIDR", type: "string", required: true, helpText: "e.g. 10.0.0.0/16" }],
  },
  subnet: {
    kind: "subnet",
    label: "Subnet",
    pluralLabel: "Subnets",
    category: "networking",
    icon: Waypoints,
    listColumns: [
      { key: "spec.vpcId", label: "VPC" },
      { key: "spec.cidr", label: "CIDR" },
      { key: "spec.type", label: "Type" },
      { key: "status.gateway", label: "Gateway" },
    ],
    searchableFields: ["spec.vpcId", "spec.cidr"],
    fields: [
      { key: "vpcId", label: "VPC", type: "reference", referenceKind: "vpc", required: true },
      { key: "cidr", label: "CIDR", type: "string", required: true },
      { key: "type", label: "Type", type: "enum", enumValues: ["public", "private"], helpText: "Default private" },
    ],
  },
  security_group: {
    kind: "security_group",
    label: "Security group",
    pluralLabel: "Security groups",
    category: "security",
    icon: ShieldCheck,
    listColumns: [
      { key: "spec.vpcId", label: "VPC" },
      { key: "spec.name", label: "Name" },
      { key: "status.chain", label: "Chain" },
    ],
    searchableFields: ["spec.vpcId", "spec.name"],
    fields: [
      { key: "vpcId", label: "VPC", type: "reference", referenceKind: "vpc", required: true },
      { key: "name", label: "Name", type: "string" },
    ],
  },
  security_group_rule: {
    kind: "security_group_rule",
    label: "Firewall rule",
    pluralLabel: "Firewall rules",
    category: "security",
    icon: ShieldAlert,
    listColumns: [
      { key: "spec.securityGroupId", label: "Security group" },
      { key: "spec.direction", label: "Direction" },
      { key: "spec.protocol", label: "Protocol" },
      { key: "spec.port", label: "Port" },
      { key: "spec.cidr", label: "CIDR" },
    ],
    searchableFields: ["spec.securityGroupId", "spec.cidr"],
    fields: [
      { key: "securityGroupId", label: "Security group", type: "reference", referenceKind: "security_group", required: true },
      { key: "direction", label: "Direction", type: "enum", enumValues: ["ingress", "egress"], required: true },
      { key: "protocol", label: "Protocol", type: "enum", enumValues: ["tcp", "udp", "icmp", "all"], required: true },
      { key: "port", label: "Port", type: "number", helpText: "TCP/UDP only; empty means any" },
      { key: "cidr", label: "CIDR", type: "string", helpText: "Source range; empty means any" },
    ],
  },
  ip_address: {
    kind: "ip_address",
    label: "IP address",
    pluralLabel: "IP addresses",
    category: "networking",
    icon: Globe,
    listColumns: [
      { key: "spec.type", label: "Type" },
      { key: "status.address", label: "Address" },
      { key: "spec.subnetId", label: "Subnet" },
      { key: "spec.computeId", label: "Compute" },
    ],
    searchableFields: ["status.address", "spec.address"],
    fields: [
      { key: "type", label: "Type", type: "enum", enumValues: ["private", "public"] },
      { key: "vpcId", label: "VPC", type: "reference", referenceKind: "vpc" },
      { key: "subnetId", label: "Subnet", type: "reference", referenceKind: "subnet" },
      { key: "computeId", label: "Compute", type: "reference", referenceKind: "compute" },
      { key: "address", label: "Requested address", type: "string", helpText: "Optional: request a specific IP" },
    ],
  },
  igw: {
    kind: "igw",
    label: "Internet gateway",
    pluralLabel: "Internet gateways",
    category: "networking",
    icon: DoorOpen,
    listColumns: [
      { key: "spec.vpcId", label: "VPC" },
      { key: "status.hostIface", label: "Host interface" },
    ],
    searchableFields: ["spec.vpcId"],
    fields: [{ key: "vpcId", label: "VPC", type: "reference", referenceKind: "vpc", required: true }],
  },
  route: {
    kind: "route",
    label: "Route",
    pluralLabel: "Routes",
    category: "networking",
    icon: RouteIcon,
    listColumns: [
      { key: "spec.vpcId", label: "VPC" },
      { key: "spec.destination", label: "Destination" },
      { key: "spec.gateway", label: "Gateway" },
    ],
    searchableFields: ["spec.vpcId", "spec.destination"],
    fields: [
      { key: "vpcId", label: "VPC", type: "reference", referenceKind: "vpc", required: true },
      { key: "subnetId", label: "Subnet", type: "reference", referenceKind: "subnet" },
      { key: "destination", label: "Destination", type: "string", required: true, helpText: "CIDR, e.g. 0.0.0.0/0" },
      { key: "gateway", label: "Gateway", type: "string", required: true, helpText: "An igw uid, \"local\", or a peer" },
    ],
  },
  kms_keyring: {
    kind: "kms_keyring",
    label: "KMS keyring",
    pluralLabel: "KMS keyrings",
    category: "security",
    icon: KeyRound,
    listColumns: [{ key: "spec.name", label: "Name" }],
    searchableFields: ["spec.name"],
    fields: [{ key: "name", label: "Name", type: "string", required: true }],
  },
  kms_key: {
    kind: "kms_key",
    label: "KMS key",
    pluralLabel: "KMS keys",
    category: "security",
    icon: Key,
    listColumns: [
      { key: "spec.keyringId", label: "Keyring" },
      { key: "spec.name", label: "Name" },
      { key: "spec.purpose", label: "Purpose" },
      { key: "spec.algorithm", label: "Algorithm" },
    ],
    searchableFields: ["spec.keyringId", "spec.name"],
    fields: [
      { key: "keyringId", label: "Keyring", type: "reference", referenceKind: "kms_keyring", required: true },
      { key: "name", label: "Name", type: "string", required: true },
      { key: "purpose", label: "Purpose", type: "string" },
      { key: "algorithm", label: "Algorithm", type: "string" },
      { key: "rotationPeriod", label: "Rotation period", type: "string" },
    ],
  },
  disk: {
    kind: "disk",
    label: "Disk",
    pluralLabel: "Disks",
    category: "storage",
    icon: HardDrive,
    listColumns: [
      { key: "spec.name", label: "Name" },
      { key: "spec.sizeMb", label: "Size (MB)" },
      { key: "status.encrypted", label: "Encrypted" },
    ],
    searchableFields: ["spec.name"],
    fields: [
      { key: "name", label: "Name", type: "string" },
      { key: "sizeMb", label: "Size (MB)", type: "number", required: true, helpText: "At least 32 when encrypted" },
      { key: "kmsKeyId", label: "KMS key", type: "reference", referenceKind: "kms_key", helpText: "Encrypts the disk at rest" },
    ],
  },
  disk_file: {
    kind: "disk_file",
    label: "Disk file",
    pluralLabel: "Disk files",
    category: "storage",
    icon: FileText,
    listColumns: [
      { key: "spec.diskId", label: "Disk" },
      { key: "spec.path", label: "Path" },
      { key: "spec.mode", label: "Mode" },
    ],
    searchableFields: ["spec.diskId", "spec.path"],
    fields: [
      { key: "diskId", label: "Disk", type: "reference", referenceKind: "disk", required: true },
      { key: "path", label: "Path", type: "string", required: true },
      { key: "content", label: "Content", type: "text" },
      { key: "mode", label: "Mode", type: "string", helpText: "e.g. 0644" },
    ],
  },
  compute: {
    kind: "compute",
    label: "Compute instance",
    pluralLabel: "Compute instances",
    category: "compute",
    icon: Cpu,
    listColumns: [
      { key: "spec.name", label: "Name" },
      { key: "spec.subnetId", label: "Subnet" },
      { key: "spec.image", label: "Image" },
      { key: "status.ip", label: "IP" },
    ],
    searchableFields: ["spec.name", "spec.image", "status.ip"],
    fields: [
      { key: "name", label: "Name", type: "string" },
      { key: "subnetId", label: "Subnet", type: "reference", referenceKind: "subnet", required: true },
      { key: "securityGroupId", label: "Security group", type: "reference", referenceKind: "security_group" },
      { key: "nodePoolId", label: "Node pool", type: "reference", referenceKind: "node_pool" },
      { key: "hostname", label: "Hostname", type: "string" },
      { key: "cpu", label: "CPU", type: "number" },
      { key: "memoryMb", label: "Memory (MB)", type: "number" },
      { key: "pidsMax", label: "Max PIDs", type: "number" },
      { key: "image", label: "Image", type: "string", required: true },
      { key: "command", label: "Command", type: "string" },
      { key: "env", label: "Environment", type: "keyValue" },
      { key: "ports", label: "Ports", type: "stringList" },
      {
        key: "disks",
        label: "Disks",
        type: "group",
        fields: [
          { key: "diskId", label: "Disk", type: "reference", referenceKind: "disk", required: true },
          { key: "mountPath", label: "Mount path", type: "string", required: true },
          { key: "readOnly", label: "Read only", type: "boolean" },
        ],
      },
      { key: "privileged", label: "Privileged", type: "boolean" },
    ],
  },
  microvm: {
    kind: "microvm",
    label: "Micro-VM",
    pluralLabel: "Micro-VMs",
    category: "compute",
    icon: Box,
    listColumns: [
      { key: "spec.name", label: "Name" },
      { key: "spec.subnetId", label: "Subnet" },
      { key: "spec.vcpus", label: "vCPUs" },
      { key: "spec.memoryMb", label: "Memory (MB)" },
      { key: "status.ip", label: "IP" },
      { key: "status.nodeName", label: "Node" },
    ],
    searchableFields: ["spec.name", "spec.image", "status.ip"],
    fields: [
      { key: "name", label: "Name", type: "string" },
      { key: "subnetId", label: "Subnet", type: "reference", referenceKind: "subnet", required: true },
      { key: "securityGroupId", label: "Security group", type: "reference", referenceKind: "security_group" },
      { key: "nodePoolId", label: "Node pool", type: "reference", referenceKind: "node_pool" },
      { key: "hostname", label: "Hostname", type: "string" },
      { key: "vcpus", label: "vCPUs", type: "number", required: true },
      { key: "memoryMb", label: "Memory (MB)", type: "number", required: true },
      {
        key: "kernelPath",
        label: "Kernel path",
        type: "string",
        required: true,
        helpText: "Absolute path to an uncompressed kernel already on the node",
      },
      { key: "initrdPath", label: "Initrd path", type: "string" },
      { key: "cmdLine", label: "Kernel command line", type: "string", helpText: "Appended to the kernel command line" },
      {
        key: "image",
        label: "Image",
        type: "string",
        required: true,
        helpText: "Boot disk: an http(s) URL or an absolute path on the node",
      },
      { key: "sshAuthorizedKey", label: "SSH authorized key", type: "string" },
      {
        key: "userData",
        label: "User data",
        type: "text",
        helpText: "cloud-init #cloud-config or #! script; replaces the generated cloud-config",
      },
    ],
  },
  acl_policy: {
    kind: "acl_policy",
    label: "ACL policy",
    pluralLabel: "ACL policies",
    category: "security",
    icon: ShieldX,
    listColumns: [
      { key: "spec.rules.length", label: "Rules" },
      { key: "status.appliedRules", label: "Applied" },
    ],
    searchableFields: [],
    fields: [
      {
        key: "rules",
        label: "Rules",
        type: "group",
        required: true,
        fields: [
          { key: "action", label: "Action", type: "enum", enumValues: ["allow", "deny"], required: true },
          { key: "protocol", label: "Protocol", type: "enum", enumValues: ["all", "tcp", "udp", "icmp"] },
          { key: "port", label: "Port", type: "number" },
          { key: "cidr", label: "CIDR", type: "string" },
          { key: "rateLimit", label: "Rate limit", type: "string", helpText: "iptables limit expression, e.g. 10/second" },
        ],
      },
    ],
  },
  dns_zone: {
    kind: "dns_zone",
    label: "DNS zone",
    pluralLabel: "DNS zones",
    category: "dns",
    icon: Globe,
    listColumns: [
      { key: "spec.domain", label: "Domain" },
      { key: "spec.visibility", label: "Visibility" },
      { key: "spec.vpcIds.length", label: "VPCs" },
    ],
    searchableFields: ["spec.domain"],
    fields: [
      { key: "name", label: "Name", type: "string" },
      { key: "domain", label: "Domain", type: "string", required: true },
      { key: "visibility", label: "Visibility", type: "enum", enumValues: ["public", "private"], helpText: "Default private" },
      { key: "vpcIds", label: "VPC uids", type: "stringList", helpText: "Private zones only: which VPCs resolve it" },
    ],
  },
  dns_record: {
    kind: "dns_record",
    label: "DNS record",
    pluralLabel: "DNS records",
    category: "dns",
    icon: Tag,
    listColumns: [
      { key: "spec.zoneId", label: "Zone" },
      { key: "spec.name", label: "Name" },
      { key: "spec.type", label: "Type" },
      { key: "spec.records.length", label: "Values" },
    ],
    searchableFields: ["spec.zoneId", "spec.name"],
    fields: [
      { key: "zoneId", label: "Zone", type: "reference", referenceKind: "dns_zone", required: true },
      { key: "name", label: "Name", type: "string", required: true },
      {
        key: "type",
        label: "Type",
        type: "enum",
        enumValues: ["A", "AAAA", "CNAME", "TXT", "MX", "NS", "SRV", "PTR", "CAA"],
        required: true,
      },
      { key: "ttl", label: "TTL", type: "number" },
      { key: "records", label: "Values", type: "stringList", required: true },
    ],
  },
  peering: {
    kind: "peering",
    label: "VPC peering",
    pluralLabel: "VPC peerings",
    category: "networking",
    icon: Link2,
    listColumns: [
      { key: "spec.vpc1Id", label: "VPC 1" },
      { key: "spec.vpc2Id", label: "VPC 2" },
    ],
    searchableFields: ["spec.vpc1Id", "spec.vpc2Id"],
    fields: [
      { key: "vpc1Id", label: "VPC 1", type: "reference", referenceKind: "vpc", required: true },
      { key: "vpc2Id", label: "VPC 2", type: "reference", referenceKind: "vpc", required: true },
    ],
  },
  load_balancer: {
    kind: "load_balancer",
    label: "Load balancer",
    pluralLabel: "Load balancers",
    category: "loadbalancing",
    icon: Scale,
    listColumns: [
      { key: "spec.vpcId", label: "VPC" },
      { key: "spec.port", label: "Port" },
      { key: "spec.protocol", label: "Protocol" },
      { key: "status.address", label: "Address" },
    ],
    searchableFields: ["spec.name", "status.address"],
    fields: [
      { key: "name", label: "Name", type: "string" },
      { key: "vpcId", label: "VPC", type: "reference", referenceKind: "vpc", required: true },
      { key: "address", label: "Address", type: "string" },
      { key: "port", label: "Port", type: "number", helpText: "Layer-4 port; leave empty to serve through lb_listeners only" },
      { key: "protocol", label: "Protocol", type: "enum", enumValues: ["tcp", "udp"], helpText: "Default tcp" },
      {
        key: "algorithm",
        label: "Algorithm",
        type: "enum",
        enumValues: ["round_robin", "least_conn", "source"],
        helpText: "Default round_robin",
      },
      { key: "publicIpId", label: "Public IP", type: "reference", referenceKind: "ip_address" },
    ],
  },
  lb_backend: {
    kind: "lb_backend",
    label: "LB backend",
    pluralLabel: "LB backends",
    category: "loadbalancing",
    icon: Target,
    listColumns: [
      { key: "spec.lbId", label: "Load balancer" },
      { key: "spec.computeId", label: "Compute" },
      { key: "spec.port", label: "Port" },
      { key: "spec.weight", label: "Weight" },
    ],
    searchableFields: ["spec.lbId", "spec.computeId"],
    fields: [
      { key: "lbId", label: "Load balancer", type: "reference", referenceKind: "load_balancer", required: true },
      { key: "computeId", label: "Compute", type: "reference", referenceKind: "compute", required: true },
      { key: "port", label: "Port", type: "number", required: true },
      { key: "weight", label: "Weight", type: "number" },
    ],
  },
  lb_target_group: {
    kind: "lb_target_group",
    label: "Target group",
    pluralLabel: "Target groups",
    category: "loadbalancing",
    icon: Layers,
    listColumns: [
      { key: "spec.vpcId", label: "VPC" },
      { key: "spec.protocol", label: "Protocol" },
      { key: "spec.port", label: "Port" },
      { key: "status.targets.length", label: "Targets" },
    ],
    searchableFields: ["spec.vpcId"],
    fields: [
      { key: "vpcId", label: "VPC", type: "reference", referenceKind: "vpc", required: true },
      { key: "protocol", label: "Protocol", type: "enum", enumValues: ["http", "https", "tcp"], helpText: "Default http" },
      { key: "port", label: "Port", type: "number", required: true, helpText: "The targets' port, unless a target names its own" },
      {
        key: "backendCaId",
        label: "Backend CA",
        type: "string",
        helpText: "https only: ssl_ca uid verifying the targets; empty trusts the platform CAs",
      },
      { key: "serverName", label: "Server name", type: "string", helpText: "https only; empty uses the request's host" },
      {
        key: "healthCheck.protocol",
        label: "Health check protocol",
        type: "enum",
        enumValues: ["http", "https", "tcp"],
        helpText: "Defaults to the group's protocol",
      },
      { key: "healthCheck.path", label: "Health check path", type: "string", helpText: "Default /; none for tcp" },
      { key: "healthCheck.port", label: "Health check port", type: "number", helpText: "Empty probes the traffic port" },
      { key: "healthCheck.intervalSeconds", label: "Health check interval (s)", type: "number", helpText: "Default 5" },
      { key: "healthCheck.timeoutSeconds", label: "Health check timeout (s)", type: "number", helpText: "Default 2" },
      { key: "healthCheck.healthyThreshold", label: "Healthy threshold", type: "number", helpText: "Default 2" },
      { key: "healthCheck.unhealthyThreshold", label: "Unhealthy threshold", type: "number", helpText: "Default 3" },
    ],
  },
  lb_target: {
    kind: "lb_target",
    label: "Target",
    pluralLabel: "Targets",
    category: "loadbalancing",
    icon: Crosshair,
    listColumns: [
      { key: "spec.targetGroupId", label: "Target group" },
      { key: "spec.computeId", label: "Compute" },
      { key: "spec.port", label: "Port" },
      { key: "spec.weight", label: "Weight" },
    ],
    searchableFields: ["spec.targetGroupId", "spec.computeId"],
    fields: [
      { key: "targetGroupId", label: "Target group", type: "reference", referenceKind: "lb_target_group", required: true },
      { key: "computeId", label: "Compute", type: "reference", referenceKind: "compute", required: true },
      { key: "port", label: "Port", type: "number", helpText: "Empty keeps the group's port" },
      { key: "weight", label: "Weight", type: "number", helpText: "1 to 1000, default 1" },
    ],
  },
  lb_listener: {
    kind: "lb_listener",
    label: "Listener",
    pluralLabel: "Listeners",
    category: "loadbalancing",
    icon: Radio,
    listColumns: [
      { key: "spec.loadBalancerId", label: "Load balancer" },
      { key: "spec.protocol", label: "Protocol" },
      { key: "spec.port", label: "Port" },
      { key: "spec.defaultTargetGroupId", label: "Default target group" },
      { key: "spec.rules.length", label: "Rules" },
    ],
    searchableFields: ["spec.loadBalancerId", "spec.defaultTargetGroupId"],
    fields: [
      { key: "loadBalancerId", label: "Load balancer", type: "reference", referenceKind: "load_balancer", required: true },
      { key: "port", label: "Port", type: "number", required: true },
      { key: "protocol", label: "Protocol", type: "enum", enumValues: ["http", "https", "tls", "tcp"], required: true },
      {
        key: "tlsMode",
        label: "TLS mode",
        type: "enum",
        enumValues: ["terminate", "reencrypt", "passthrough"],
        helpText: "https: terminate (default) or reencrypt; tls: passthrough",
      },
      {
        key: "certificateIds",
        label: "Certificate uids",
        type: "stringList",
        helpText: "https only: the ssl_certs served, picked by SNI",
      },
      {
        key: "defaultTargetGroupId",
        label: "Default target group",
        type: "reference",
        referenceKind: "lb_target_group",
        required: true,
      },
      {
        key: "rules",
        label: "Rules",
        type: "group",
        helpText: "Route by host and/or path prefix (SNI host only on tls); not on tcp",
        fields: [
          { key: "host", label: "Host", type: "string" },
          { key: "pathPrefix", label: "Path prefix", type: "string" },
          { key: "targetGroupId", label: "Target group", type: "reference", referenceKind: "lb_target_group", required: true },
        ],
      },
    ],
  },
  waf_policy: {
    kind: "waf_policy",
    label: "WAF policy",
    pluralLabel: "WAF policies",
    category: "security",
    icon: AlertTriangle,
    listColumns: [
      { key: "spec.targetType", label: "Target type" },
      { key: "spec.targetId", label: "Target" },
      { key: "status.chain", label: "Chain" },
    ],
    searchableFields: ["spec.targetId"],
    fields: [
      { key: "name", label: "Name", type: "string" },
      { key: "targetType", label: "Target type", type: "enum", enumValues: ["igw", "subnet", "compute"], required: true },
      { key: "targetId", label: "Target", type: "string", required: true, helpText: "UID of the igw/subnet/compute above" },
      { key: "logEnabled", label: "Log enabled", type: "boolean" },
    ],
  },
  waf_rule: {
    kind: "waf_rule",
    label: "WAF rule",
    pluralLabel: "WAF rules",
    category: "security",
    icon: AlertTriangle,
    listColumns: [
      { key: "spec.policyId", label: "Policy" },
      { key: "spec.matchType", label: "Match type" },
      { key: "spec.action", label: "Action" },
    ],
    searchableFields: ["spec.policyId"],
    fields: [
      { key: "policyId", label: "Policy", type: "reference", referenceKind: "waf_policy", required: true },
      { key: "priority", label: "Priority", type: "number" },
      { key: "matchType", label: "Match type", type: "string", required: true },
      { key: "matchValue", label: "Match value", type: "string" },
      { key: "action", label: "Action", type: "enum", enumValues: ["block", "allow", "log", "ratelimit"], required: true },
      { key: "rateLimit", label: "Rate limit", type: "number" },
      { key: "rateWindow", label: "Rate window", type: "number" },
    ],
  },
  node: {
    kind: "node",
    label: "Node",
    pluralLabel: "Nodes",
    category: "compute",
    icon: Server,
    listColumns: [
      { key: "spec.hostname", label: "Hostname" },
      { key: "spec.address", label: "Address" },
      { key: "spec.capacity.cpus", label: "CPUs" },
      { key: "spec.capacity.memoryMb", label: "Memory (MB)" },
    ],
    searchableFields: ["spec.hostname", "spec.address"],
    fields: [
      { key: "hostname", label: "Hostname", type: "string", required: true },
      { key: "address", label: "Address", type: "string", required: true },
      { key: "labels", label: "Labels", type: "keyValue" },
      { key: "capacity.cpus", label: "CPUs", type: "number", required: true },
      { key: "capacity.memoryMb", label: "Memory (MB)", type: "number", required: true },
      { key: "capacity.maxPods", label: "Max pods", type: "number" },
    ],
  },
  node_pool: {
    kind: "node_pool",
    label: "Node pool",
    pluralLabel: "Node pools",
    category: "compute",
    icon: Boxes,
    listColumns: [
      { key: "spec.name", label: "Name" },
      { key: "status.readyNodes", label: "Ready" },
      { key: "status.totalNodes", label: "Total" },
    ],
    searchableFields: ["spec.name"],
    fields: [
      { key: "name", label: "Name", type: "string", required: true },
      { key: "nodeSelector", label: "Node selector", type: "keyValue" },
      { key: "minNodes", label: "Min nodes", type: "number" },
      { key: "maxNodes", label: "Max nodes", type: "number" },
    ],
  },
  organization: {
    kind: "organization",
    label: "Organization",
    pluralLabel: "Organizations",
    category: "resourceManagement",
    icon: Building2,
    scoped: false,
    listColumns: [{ key: "spec.displayName", label: "Display name" }],
    searchableFields: ["spec.displayName"],
    fields: [{ key: "displayName", label: "Display name", type: "string", required: true }],
  },
  folder: {
    kind: "folder",
    label: "Folder",
    pluralLabel: "Folders",
    category: "resourceManagement",
    icon: Folder,
    scoped: false,
    listColumns: [
      { key: "spec.displayName", label: "Display name" },
      { key: "spec.parentKind", label: "Parent kind" },
      { key: "spec.parentId", label: "Parent" },
    ],
    searchableFields: ["spec.displayName"],
    fields: [
      { key: "displayName", label: "Display name", type: "string", required: true },
      { key: "parentKind", label: "Parent kind", type: "enum", enumValues: ["organization", "folder"], required: true },
      {
        key: "parentId",
        label: "Parent ID",
        type: "string",
        required: true,
        helpText: "UID of the parent organization or folder",
      },
    ],
  },
  project: {
    kind: "project",
    label: "Project",
    pluralLabel: "Projects",
    category: "resourceManagement",
    icon: FolderKanban,
    scoped: false,
    listColumns: [
      { key: "spec.displayName", label: "Display name" },
      { key: "spec.parentKind", label: "Parent kind" },
      { key: "spec.parentId", label: "Parent" },
    ],
    searchableFields: ["spec.displayName"],
    fields: [
      { key: "displayName", label: "Display name", type: "string", required: true },
      { key: "parentKind", label: "Parent kind", type: "enum", enumValues: ["organization", "folder"], required: true },
      {
        key: "parentId",
        label: "Parent ID",
        type: "string",
        required: true,
        helpText: "UID of the parent organization or folder",
      },
    ],
  },
  iam_binding: {
    kind: "iam_binding",
    label: "IAM binding",
    pluralLabel: "IAM bindings",
    category: "resourceManagement",
    icon: UserCog,
    scoped: false,
    listColumns: [
      { key: "spec.role", label: "Role" },
      { key: "spec.resource.kind", label: "Target kind" },
      { key: "spec.resource.uid", label: "Target" },
    ],
    searchableFields: ["spec.resource.uid"],
    fields: [
      {
        key: "resource.kind",
        label: "Target kind",
        type: "enum",
        enumValues: ["organization", "folder", "project"],
        required: true,
      },
      {
        key: "resource.uid",
        label: "Target UID",
        type: "string",
        required: true,
        helpText: "UID of the organization, folder or project to grant access on",
      },
      {
        key: "role",
        label: "Role",
        type: "enum",
        enumValues: ["roles/viewer", "roles/editor", "roles/owner"],
        required: true,
      },
      {
        key: "members",
        label: "Members",
        type: "stringList",
        required: true,
        helpText: 'Each entry must be "<kind>:<id>", e.g. "user:alice"',
      },
    ],
  },
};
