# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Chris <goabonga@pm.me>

# render_pkgbuild: shared between build-archlinux.sh (a local file:// source,
# for the downloadable .pkg.tar.zst attached to each GitHub Release) and
# push-aur.sh (the real https:// GitHub tag tarball, for the PKGBUILD
# actually published to the AUR) - one template, so the two never drift.
# Sourced, not executed; depends on packaging/components.sh's tables already
# being in scope.

render_pkgbuild() {
  local pkg="$1" version="$2" dir="$3" bin="$4" svc="$5" out="$6" source_line="$7" sha256="$8"
  local extended
  extended=$(printf '%s' "${DESCRIPTION[$pkg]}" | tr '\n' ' ')

  local extra_build="" extra_pkg="" extra_bin extra_dir extra_name
  for extra_bin in ${EXTRA_BINARIES[$pkg]:-}; do
    IFS=: read -r extra_dir extra_name <<<"$extra_bin"
    extra_build+=$'\n'"  go build -trimpath -ldflags=\"-s -w\" -o \"$extra_name\" \"./cmd/$extra_dir/\""
    extra_pkg+=$'\n'"  install -Dm755 \"$extra_name\" \"\$pkgdir/usr/bin/$extra_name\""
  done

  local unit_pkg="" extra_unit
  if [ -n "$svc" ]; then
    unit_pkg="  install -Dm644 \"deploy/systemd/$svc.service\" \"\$pkgdir/usr/lib/systemd/system/$svc.service\""
    for extra_unit in ${EXTRA_UNITS[$pkg]:-}; do
      unit_pkg+=$'\n'"  install -Dm644 \"deploy/systemd/$extra_unit\" \"\$pkgdir/usr/lib/systemd/system/$extra_unit\""
    done
    # systemd-sysusers, not a postinst script: Arch packages declare system
    # users/groups declaratively and let systemd-sysusers.service (or the
    # .install hook below) apply them, rather than running adduser by hand.
    # Matches the .deb postinst's "infra, no login, no home it owns" account.
    unit_pkg+=$'\n'"  install -Dm644 /dev/stdin \"\$pkgdir/usr/lib/sysusers.d/$pkg.conf\" <<<'u infra - \"infra service account\" /var/lib/infra /usr/sbin/nologin'"
  fi

  cat >"$out" <<PKGBUILD
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Chris <goabonga@pm.me>
# Generated by packaging/archlinux-pkgbuild.sh - do not edit by hand; a
# change here belongs in that script or in packaging/components.sh instead,
# so the .deb and every AUR package stay in sync.

pkgname=$pkg
pkgver=$version
pkgrel=1
pkgdesc="${SUMMARY[$pkg]}: $extended"
arch=('x86_64' 'aarch64')
url="https://github.com/goabonga/infrastructure"
license=('MIT')
makedepends=('go')
# !debug: the binaries are already built -s -w (no debug symbols, the same
# reason the .deb carries a lintian override for statically-linked-binary),
# so makepkg's gdb-add-index step has nothing to index.
options=('!debug')
source=($source_line)
sha256sums=('$sha256')

build() {
  cd "\$srcdir"/*/
  export CGO_ENABLED=0
  # -trimpath: without it, the binary embeds \$srcdir's absolute path
  # (makepkg's build-time temp dir), which makepkg's own packaging checks
  # then flag as a leaked build-root reference.
  go build -trimpath -ldflags="-s -w" -o "$bin" "./cmd/$dir/"$extra_build
}

package() {
  cd "\$srcdir"/*/
  install -Dm755 "$bin" "\$pkgdir/usr/bin/$bin"$extra_pkg
  install -Dm644 LICENSE "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
$unit_pkg
}
PKGBUILD
}
