# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Chris <goabonga@pm.me>

name: zizmor-example

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  example:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-go@v6
